### ISSUE TITLE
It's not an issue, I just don't know where to comment

### ISSUE THREAD

**Issue by blaisexen** [zbyna/opencv-lazarus#1]
I'm glad there is opencv-Lazarus!

without mentioning where was this files from: ipl.pas and opencv.pas, I think it's from here, if I'm not mistaken! 4 Years Ago!
 
https://github.com/arturobriones/EmbarcaderoXE3_OpenCV/tree/master/opencvdelphi

**Comment by zbyna** [comment]
Yes, it is possible.  I will add your findings to README.md : https://github.com/zbyna/opencv-lazarus/commit/599fd83e9ebd8ec4444f3f60f9cd7bff52a8d5a1
