### ISSUE TITLE
Testes Demo

### ISSUE THREAD

**Issue by blaisexen** [zbyna/opencv-lazarus#4]
hi,

I tested the demo1 under windows with some opencv dlls, may I now if demo1 will also run under linux or macos?

**Comment by zbyna** [comment]
Hi,
if you are able to compile under linux, the demo should run fine. But to tell the truth I did not try in Linux or mac.

**Comment by blaisexen** [comment]
lol, thanks, but I'm just asking, I still don't have Linux or Mac, lol

**Comment by blaisexen** [comment]
anyway, I found out and place the demos here,
https://sourceforge.net/projects/delphi-opencv-face-detection/
